spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/menu
    username: ${your_username}
    password: ${your_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

jwt:
  secret_key: ${jwt.secret_key}

admin:
  username : ${admin.username}
  password : ${admin.password}

file:
  path: ./upload/

kakao:
  client_id : ${kakao.client_id}
  redirect_uri : ${kakao.redirect_uri}

naver:
  client_id : ${naver.client_id}
  client_secret : ${naver.client_secret}
  redirect_uri : ${naver.redirect_uri}

google :
  client_id : ${google.client_id}
  client_secret : ${google.client_secret}
  redirect_uri : ${google.redirect_uri}