spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/menu
    username: ${your_username}
    password: ${your_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
jwt:
  secret_key: ${jwt.secret_key}

admin:
  username : ${admin.username}
  password : ${admin.password}

file:
  path: C:\Users\user\intellij-workspace\TMProjcet\upload
