spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/menu
    username: ${your_username}
    password: ${your_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true

jwt:
  secret_key: ${jwt.secret_key}

admin:
  username : ${admin.username}
  password : ${admin.password}

file:
  path: ./upload/

kakao:
  client_id : 8bbcb11360f192ffb599e80a0fc3489a
  redirect_uri : http://localhost:8080/api/member/kakao/callback

naver:
  client_id : 3jo14itcz2ELeaKj8BPQ
  client_secret : DUp0cF33Dw
  redirect_uri : http://localhost:8080/api/member/naver/callback

google :
  client_id : 807257127729-2eg30f8m4cq2ngtm1d6q4o2o68p5q8bm.apps.googleusercontent.com
  client_secret : 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
  redirect_uri : http://localhost:8080/api/member/google/callback